# Visit https://goreleaser.com for documentation on how to customize this
# file.
project_name: terraform-provider-iru

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action, make sure you should use
      # --batch --pinentry-mode loopback --no-tty --local-user {{ .Env.GPG_FINGERPRINT }}
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # GPG key fingerprint
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  skip: true
